version: '3'

services:
  jenkins:
    container_name: jenkins_php
    build:
      context: .
    image: jenkins/php
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "5000:5000"

volumes:
  jenkins_home:
